AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local SAM template for testing HelloTasks Lambda

Resources:
  HelloTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.12
      CodeUri: src/
      Timeout: 10
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
